//
// Generated by dtk
// Translation Unit: d_a_daiocta.cpp
//

#include "d/actor/d_a_daiocta.h"
#include "d/d_com_inf_game.h"
#include "d/d_cc_d.h"
#include "d/d_procname.h"
#include "d/d_lib.h"
#include "d/d_jnt_hit.h"
#include "d/actor/d_a_bomb.h"
#include "m_Do/m_Do_hostIO.h"

class daDaiocta_HIO_c : mDoHIO_entry_c {
public:
    daDaiocta_HIO_c();

    char m0004;
    char m0005;
    char m0006;
    char m0007;

    char m0008;
    char m0009;
    char m000A;
    char m000B;

    s16 m000C;
    s16 m000E;

    char pad[0xC];

    cXyz m001C;
    cXyz m0028;
    cXyz m0034;
    cXyz m0040;
    cXyz m004C;
    cXyz m0058;
    cXyz m0064;
    float m0070;
    float m0074;
};

static daDaiocta_HIO_c l_HIO;

const int daDaiocta_c::m_heapsize = 0x0000F740;
const char daDaiocta_c::m_arc_name[] = "daiocta";

const dCcD_SrcSph daDaiocta_c::m_sph_src = {
    // dCcD_SrcGObjInf
    {
        /* Flags             */ 0,
        /* SrcObjAt  Type    */ 0,
        /* SrcObjAt  Atp     */ 0,
        /* SrcObjAt  SPrm    */ 0,
        /* SrcObjTg  Type    */ 0xFF1DFEBF,
        /* SrcObjTg  SPrm    */ TG_SPRM_SET | TG_SPRM_IS_OTHER,
        /* SrcObjCo  SPrm    */ 0x79,
        /* SrcGObjAt Se      */ 0,
        /* SrcGObjAt HitMark */ 0,
        /* SrcGObjAt Spl     */ 0,
        /* SrcGObjAt Mtrl    */ 0,
        /* SrcGObjAt SPrm    */ 0,
        /* SrcGObjTg Se      */ 0x23,
        /* SrcGObjTg HitMark */ 0,
        /* SrcGObjTg Spl     */ 0,
        /* SrcGObjTg Mtrl    */ 0,
        /* SrcGObjTg SPrm    */ 0,
        /* SrcGObjCo SPrm    */ 0,
    },
    // cM3dGSphS
    {
        /* Center */ 0.0f, 0.0f, 0.0f,
        /* Radius */ 180.0f,
    }
};

const dCcD_SrcCps daDaiocta_c::m_cps_src = {
    // dCcD_SrcGObjInf
    {
        /* Flags             */ 0,
        /* SrcObjAt  Type    */ 0,
        /* SrcObjAt  Atp     */ 0,
        /* SrcObjTg  SPrm    */ 0,
        /* SrcObjTg  Type    */ 0xFF1DFEBF,
        /* SrcObjTg  SPrm    */ TG_SPRM_SET | TG_SPRM_IS_OTHER,
        /* SrcObjCo  SPrm    */ 0x79,
        /* SrcGObjAt Se      */ 0,
        /* SrcGObjAt HitMark */ 0,
        /* SrcGObjAt Spl     */ 0,
        /* SrcGObjAt Mtrl    */ 0,
        /* SrcGObjAt SPrm    */ 0,
        /* SrcGObjTg Se      */ 0x23,
        /* SrcGObjTg HitMark */ 0,
        /* SrcGObjTg Spl     */ 0,
        /* SrcGObjTg Mtrl    */ 0,
        /* SrcGObjTg SPrm    */ 0,
        /* SrcGObjCo SPrm    */ 0,
    },
    // cM3dGCpsS
    {
        /* Start  */ 0.0f, 0.0f, 0.0f,
        /* End    */ 0.0f, 0.0f, 0.0f,
        /* Radius */ 60.0f,
    }
};

__jnt_hit_data_c search_data = {
    // TODO: fill this in
};

/* 000000EC-000002B0       .text __ct__15daDaiocta_HIO_cFv */
daDaiocta_HIO_c::daDaiocta_HIO_c() {
    /* Nonmatching */
    int f = daDaiocta_c::m_heapsize;

    m0004 = 0;
    m0008 = 0;
    m0006 = 0;
    m0005 = 0;

    m001C.set(600.0f, 500.0f, 450.0f);
    m0028.set(350.0f, 350.0f, 300.0f);
    m0034.set(60.0f, 60.0f, 60.0f);
    m0040.set(60.0f, 60.0f, 60.0f);
    m004C.set(60.0f, 60.0f, 60.0f);
    m0058.set(60.0f, 100.0f, 100.0f);
    m0064.set(250.0f, 100.0f, 150.0f);
    m0070 = 100.0f;
    m0074 = 150.0f;

    m000C = 0x1E;
    m000E = 0x3C;

    // TODO: finish this
}

/* 00000334-00000358       .text coHit_CB__FP10fopAc_ac_cP12dCcD_GObjInfP10fopAc_ac_cP12dCcD_GObjInf */
void coHit_CB(fopAc_ac_c* daiocta, dCcD_GObjInf* p2, fopAc_ac_c* other, dCcD_GObjInf* p3) {
    static_cast<daDaiocta_c*>(daiocta)->_coHit(other);
}

/* 00000358-000003DC       .text _coHit__11daDaiocta_cFP10fopAc_ac_c */
void daDaiocta_c::_coHit(fopAc_ac_c* other) {
    if (other != NULL && other->base.mProcName == 0x128)
    {
        if ((m056C == 2 || m056C == 4 || m056C == 1 || m056C == 3) && static_cast<daBomb_c*>(other)->chk_state(daBomb_c::STATE_4))
        {
            modeProc(proc_ZERO_e, mode_FOUR_e);
        }
    }
}

/* 000003DC-00000470       .text nodeControl_CB__FP7J3DNodei */
static BOOL nodeControl_CB(J3DNode* node, int p2) {
    /* Nonmatching */
    if (p2 == 0)
    {
        J3DModel* mdl = j3dSys.mModel;

        daDaiocta_c* daiocta = (daDaiocta_c*)mdl->getUserArea();
        JUT_ASSERT(0x1A4, daiocta != NULL)

        daiocta->_nodeControl(node, mdl);
    }

    return TRUE;
}

/* 00000470-0000066C       .text _nodeControl__11daDaiocta_cFP7J3DNodeP8J3DModel */
void daDaiocta_c::_nodeControl(J3DNode* node, J3DModel* mdl) {
    /* Nonmatching */
    u16 jntIdx = static_cast<J3DJoint*>(node)->getJntNo();
    mDoMtx_stack_c::copy(mdl->mpNodeMtx[jntIdx]);

    m290[jntIdx].x = mDoMtx_stack_c::now[0][3];
    m290[jntIdx].y = mDoMtx_stack_c::now[1][3];
    m290[jntIdx].z = mDoMtx_stack_c::now[2][3];

    cXyz pos;

    switch(jntIdx)
    {
        case 6:
            pos.set(450.0f, 0.0f, 0.0f);
            mDoMtx_stack_c::multVec(&pos, &m21B8);
        break;
        case 7:
            pos.set(300.0f, 0.0f, 0.0f);
            mDoMtx_stack_c::multVec(&pos, &m21D0);
        break;
        case 8:
            pos.set(300.0f, 0.0f, 0.0f);
            mDoMtx_stack_c::multVec(&pos, &m21E8);
        break;
        case 9:
            pos.set(300.0f, -200.0f, 0.0f);
            mDoMtx_stack_c::multVec(&pos, &m21C4);
        break;
        case 10:
            pos.set(300.0f, 200.0f, 0.0f);
            mDoMtx_stack_c::multVec(&pos, &m21DC);
        break;
        case 0x14:
            pos.set(450.0f, 0.0f, 0.0f);
            mDoMtx_stack_c::multVec(&pos, &m2434);
        break;
        case 0x1E:
            pos.set(450.0f, 0.0f, 0.0f);
            mDoMtx_stack_c::multVec(&pos, &m21A0);
        break;
        case 0x24:
            pos.set(450.0f, 0.0f, 0.0f);
            mDoMtx_stack_c::multVec(&pos, &m21AC);
        break;
    }

    mDoMtx_stack_c::copy(j3dSys.mCurrentMtx);
    mDoMtx_stack_c::copy(mdl->mpNodeMtx[jntIdx]);
}

/* 0000066C-0000068C       .text createHeap_CB__FP10fopAc_ac_c */
static BOOL createHeap_CB(fopAc_ac_c* actor) {
    static_cast<daDaiocta_c*>(actor)->_createHeap();
}

/* 0000068C-00000708       .text _createHeap__11daDaiocta_cFv */
bool daDaiocta_c::_createHeap() {
    if (!createBodyHeap())
    {
        return false;
    }

    if (!createSuikomiHeap())
    {
        return false;
    }

    if (!createAwaHeap())
    {
        return false;
    }

    BOOL result = createArrowHitHeap();
    return result != FALSE;
}

/* 00000708-000009B8       .text createAwaHeap__11daDaiocta_cFv */
BOOL daDaiocta_c::createAwaHeap() {
    /* Nonmatching */
    J3DModelData* modelData = (J3DModelData*)dComIfG_getObjectRes(m_arc_name, 0x12);
    JUT_ASSERT(0x204, modelData != NULL)

    J3DAnmTransform* bck = (J3DAnmTransform*)dComIfG_getObjectRes(m_arc_name, 0x0A);
    JUT_ASSERT(0x208, bck != NULL)

    J3DAnmTextureSRTKey* btk = (J3DAnmTextureSRTKey*)dComIfG_getObjectRes(m_arc_name, 0x25);
    JUT_ASSERT(0x20C, btk != NULL)

    J3DAnmTevRegKey* brk = (J3DAnmTevRegKey*)dComIfG_getObjectRes(m_arc_name, 0x1C);
    JUT_ASSERT(0x210, brk != NULL)

    for (int i = 0; i < 0x1E; i++)
    {
        mModels[i] = mDoExt_J3DModel__create(modelData, 0x80000, 0x11000222);
        if (mModels[i] == NULL)
        {
            return FALSE;
        }

        if (mBcks[i].init(modelData, bck, TRUE, 0, 1.0f, 0, -1, false) == 0)
        {
            return FALSE;
        }
        if (mBtks[i].init(modelData, btk, TRUE, 0, 1.0f, 0, -1, false, 0) == 0)
        {
            return FALSE;
        }
        if (mBrks[i].init(modelData, brk, TRUE, 0, 1.0f, 0, -1, false, 0) == 0)
        {
            return FALSE;
        }
    }

    return TRUE;
}

/* 000009B8-00000ABC       .text createSuikomiHeap__11daDaiocta_cFv */
BOOL daDaiocta_c::createSuikomiHeap() {
    /* Nonmatching */
    J3DModelData* modelData = (J3DModelData*)dComIfG_getObjectRes(m_arc_name, 0x13);
    JUT_ASSERT(0x227, modelData != NULL)

    mSuikomiModel = mDoExt_J3DModel__create(modelData, 0x80000, 0x11000222);
    if (mSuikomiModel == NULL)
    {
        return FALSE;
    }

    if (!dLib_brkInit(modelData, &mSuikomiBrk, m_arc_name, 0x1D) || !dLib_btkInit(modelData, &mSuikomiBtk, m_arc_name, 0x26))
    {
        return FALSE;
    }

    return TRUE;
}

/* 00000ABC-00000C04       .text createBodyHeap__11daDaiocta_cFv */
BOOL daDaiocta_c::createBodyHeap() {
    /* Nonmatching */
    J3DModelData* modelData = (J3DModelData*)dComIfG_getObjectRes(m_arc_name, 0x11);
    JUT_ASSERT(0x243, modelData != NULL)

    if (!dLib_brkInit(modelData, &mBodyBrk, m_arc_name, 0x20))
    {
        return FALSE;
    }

    mBodyMorf = new mDoExt_McaMorf(modelData, NULL, NULL, NULL, -1, 1.0f, 0, -1, 1, NULL, 0x80000, 0x11000222);
    if (mBodyMorf == NULL || mBodyMorf->mpModel == NULL)
    {
        return FALSE;
    }

    mBodyMorf->getModel()->setUserArea(reinterpret_cast<u32>(this));
    return TRUE;
}

/* 00000C04-00000C64       .text createArrowHitHeap__11daDaiocta_cFv */
BOOL daDaiocta_c::createArrowHitHeap() {
    /* Nonmatching */
    mJntHit = JntHit_create(mBodyMorf->getModel(), &search_data, 0x11);

    if (mJntHit == NULL)
    {
        return FALSE;
    }
    
    jntHit = mJntHit;
    return TRUE;
}

/* 00000C64-00000D94       .text setMtx__11daDaiocta_cFv */
void daDaiocta_c::setMtx() {
    /* Nonmatching */
}

/* 00000D94-00000E2C       .text setSuikomiMtx__11daDaiocta_cFv */
void daDaiocta_c::setSuikomiMtx() {
    /* Nonmatching */
}

/* 00000E2C-00000EDC       .text setAwaMtx__11daDaiocta_cFv */
void daDaiocta_c::setAwaMtx() {
    /* Nonmatching */
}

/* 00000EDC-00000F70       .text initMtx__11daDaiocta_cFv */
void daDaiocta_c::initMtx() {
    /* Nonmatching */
}

/* 00000F70-0000116C       .text setEffect__11daDaiocta_cFUs */
void daDaiocta_c::setEffect(unsigned short) {
    /* Nonmatching */
}

/* 0000116C-0000129C       .text setAwaRandom__11daDaiocta_cFi */
void daDaiocta_c::setAwaRandom(int) {
    /* Nonmatching */
}

/* 0000129C-000013D8       .text initAwa__11daDaiocta_cFv */
void daDaiocta_c::initAwa() {
    /* Nonmatching */
}

/* 000013D8-00001548       .text execAwa__11daDaiocta_cFv */
void daDaiocta_c::execAwa() {
    /* Nonmatching */
}

/* 00001548-000015E8       .text isLivingEye__11daDaiocta_cFv */
void daDaiocta_c::isLivingEye() {
    /* Nonmatching */
}

/* 000015E8-00001684       .text isDead__11daDaiocta_cFv */
void daDaiocta_c::isDead() {
    /* Nonmatching */
}

/* 00001684-0000171C       .text isDamageEye__11daDaiocta_cFv */
void daDaiocta_c::isDamageEye() {
    /* Nonmatching */
}

/* 0000171C-000017B4       .text isDamageBombEye__11daDaiocta_cFv */
void daDaiocta_c::isDamageBombEye() {
    /* Nonmatching */
}

/* 000017B4-00001A7C       .text setRotEye__11daDaiocta_cFv */
void daDaiocta_c::setRotEye() {
    /* Nonmatching */
}

/* 00001A7C-00001EA0       .text setCollision__11daDaiocta_cFv */
void daDaiocta_c::setCollision() {
    /* Nonmatching */
}

/* 00001EA0-00001EB8       .text modeHideInit__11daDaiocta_cFv */
void daDaiocta_c::modeHideInit() {
    /* Nonmatching */
}

/* 00001EB8-00001F34       .text modeHide__11daDaiocta_cFv */
void daDaiocta_c::modeHide() {
    /* Nonmatching */
}

/* 00001F34-000020C8       .text modeAppearInit__11daDaiocta_cFv */
void daDaiocta_c::modeAppearInit() {
    /* Nonmatching */
}

/* 000020C8-0000236C       .text modeAppear__11daDaiocta_cFv */
void daDaiocta_c::modeAppear() {
    /* Nonmatching */
}

/* 0000236C-000023B0       .text modeWaitInit__11daDaiocta_cFv */
void daDaiocta_c::modeWaitInit() {
    /* Nonmatching */
}

/* 000023B0-00002458       .text modeWait__11daDaiocta_cFv */
void daDaiocta_c::modeWait() {
    /* Nonmatching */
}

/* 00002458-000024D8       .text modeDamageInit__11daDaiocta_cFv */
void daDaiocta_c::modeDamageInit() {
    /* Nonmatching */
}

/* 000024D8-000025C4       .text modeDamage__11daDaiocta_cFv */
void daDaiocta_c::modeDamage() {
    /* Nonmatching */
}

/* 000025C4-0000268C       .text modeDamageBombInit__11daDaiocta_cFv */
void daDaiocta_c::modeDamageBombInit() {
    /* Nonmatching */
}

/* 0000268C-00002778       .text modeDamageBomb__11daDaiocta_cFv */
void daDaiocta_c::modeDamageBomb() {
    /* Nonmatching */
}

/* 00002778-000028FC       .text modeDemoInit__11daDaiocta_cFv */
void daDaiocta_c::modeDemoInit() {
    /* Nonmatching */
}

/* 000028FC-00003150       .text modeDemo__11daDaiocta_cFv */
void daDaiocta_c::modeDemo() {
    /* Nonmatching */
}

/* 00003150-00003284       .text modeDeleteInit__11daDaiocta_cFv */
void daDaiocta_c::modeDeleteInit() {
    /* Nonmatching */
}

/* 00003284-000036A8       .text modeDelete__11daDaiocta_cFv */
void daDaiocta_c::modeDelete() {
    /* Nonmatching */
}

/* 000036A8-00003888       .text modeProc__11daDaiocta_cFQ211daDaiocta_c6Proc_eQ211daDaiocta_c6Mode_e */
void daDaiocta_c::modeProc(daDaiocta_c::Proc_e, daDaiocta_c::Mode_e) {
    /* Nonmatching */
}

/* 00003888-00003AF4       .text setAnm__11daDaiocta_cFv */
void daDaiocta_c::setAnm() {
    /* Nonmatching */
}

/* 00003AF4-00003B20       .text setWater__11daDaiocta_cFv */
void daDaiocta_c::setWater() {
    /* Nonmatching */
}

/* 00003B20-00003D20       .text _execute__11daDaiocta_cFv */
BOOL daDaiocta_c::_execute() {
    /* Nonmatching */
}

/* 00003D20-00003E58       .text drawAwa__11daDaiocta_cFv */
void daDaiocta_c::drawAwa() {
    /* Nonmatching */
}

/* 00003E58-00003F4C       .text drawSuikomi__11daDaiocta_cFv */
void daDaiocta_c::drawSuikomi() {
    /* Nonmatching */
}

/* 00003F4C-0000412C       .text drawDebug__11daDaiocta_cFv */
void daDaiocta_c::drawDebug() {
    /* Nonmatching */
}

/* 0000412C-00004244       .text _draw__11daDaiocta_cFv */
BOOL daDaiocta_c::_draw() {
    /* Nonmatching */
}

/* 00004244-00004364       .text getArg__11daDaiocta_cFv */
void daDaiocta_c::getArg() {
    /* Nonmatching */
}

/* 00004364-00004660       .text createInit__11daDaiocta_cFv */
void daDaiocta_c::createInit() {
    /* Nonmatching */
}

/* 00004660-00004918       .text _create__11daDaiocta_cFv */
s32 daDaiocta_c::_create() {
    /* Nonmatching */
}

/* 00005098-0000513C       .text _delete__11daDaiocta_cFv */
BOOL daDaiocta_c::_delete() {
    /* Nonmatching */
}

/* 0000513C-0000515C       .text daDaioctaCreate__FPv */
static s32 daDaioctaCreate(void*) {
    /* Nonmatching */
}

/* 0000515C-00005180       .text daDaioctaDelete__FPv */
static BOOL daDaioctaDelete(void*) {
    /* Nonmatching */
}

/* 00005180-000051A4       .text daDaioctaExecute__FPv */
static BOOL daDaioctaExecute(void*) {
    /* Nonmatching */
}

/* 000051A4-000051C8       .text daDaioctaDraw__FPv */
static BOOL daDaioctaDraw(void*) {
    /* Nonmatching */
}

/* 000051C8-000051D0       .text daDaioctaIsDelete__FPv */
static BOOL daDaioctaIsDelete(void*) {
    /* Nonmatching */
}

static actor_method_class daDaioctaMethodTable = {
    (process_method_func)daDaioctaCreate,
    (process_method_func)daDaioctaDelete,
    (process_method_func)daDaioctaExecute,
    (process_method_func)daDaioctaIsDelete,
    (process_method_func)daDaioctaDraw,
};

actor_process_profile_definition g_profile_DAIOCTA = {
    /* LayerID      */ fpcLy_CURRENT_e,
    /* ListID       */ 0x0007,
    /* ListPrio     */ fpcPi_CURRENT_e,
    /* ProcName     */ PROC_DAIOCTA,
    /* Proc SubMtd  */ &g_fpcLf_Method.base,
    /* Size         */ sizeof(daDaiocta_c),
    /* SizeOther    */ 0,
    /* Parameters   */ 0,
    /* Leaf SubMtd  */ &g_fopAc_Method.base,
    /* Priority     */ 0x00D5,
    /* Actor SubMtd */ &daDaioctaMethodTable,
    /* Status       */ fopAcStts_UNK40000_e,
    /* Group        */ fopAc_ENEMY_e,
    /* CullType     */ fopAc_CULLBOX_CUSTOM_e,
};
